### ISSUE TITLE
tag a new release with pinephone pro add smbios data patch?

### ISSUE THREAD

**Issue by ollieparanoid** [Tow-Boot/Tow-Boot#171]
Hi,

it would be great to have a new release tagged that includes https://github.com/Tow-Boot/Tow-Boot/pull/135 since without that patch alsa can't find the proper UCM config path ([pmaports#1601](https://gitlab.com/postmarketOS/pmaports/-/issues/1601)):

```
pine64-pinephonepro:~$ cat /proc/asound/cards 
 0 [PinePhonePro   ]: simple-card - PinePhonePro
                      Unknown-UnknownProduct-
```

I'm not sure what the plans for the next release are, maybe it's worth backporting this on top of the previous release?

Thanks for all the work on Tow-Boot!

**Comment by samueldr** [comment]
I'm preparing one by doing the trivial tasks I had in the TODO list, and will cut a release probably today, or else tomorrow.

**Comment by samueldr** [comment]
I have still to get a few representative devices out to test the release, which I'll do tomorrow.

In the meantime, since you have a particular issue you want to test against, you can use this build built from the current tip of `development`:

 - [URL removed]

It should basically be the build used in the release, except with the `2021.10-005-pre` version build number instead of `2021.10-005`.

**Comment by samueldr** [comment]
The new release is now up

 - https://github.com/Tow-Boot/Tow-Boot/releases/tag/release-2021.10-005

It should solve the underlying problem here.
