### ISSUE TITLE
Performing `saveenv` when booting from SPI corrupts SPI

### ISSUE THREAD

**Issue by b-** [Tow-Boot/Tow-Boot#19]
This appears to be somewhat of [a u-boot problem](https://forums.xilinx.com/t5/Embedded-Linux/Where-does-U-Boot-saveenv-to/td-p/532915), and not specifically tow-boot, but I figure an opinionated configuration might provision for this sort of thing:

I had Tow-Boot installed to SPI, and I was poking around the console, and I tried running `saveenv`, which proceeded to save environment settings to SPI, overwriting part of the loader. Which part? I don't know. It didn't say _where_ in SPI it was saving, but I presume it was an important region because now the power LED is red upon power on and nothing else happens.

Maybe `saveenv` can write to a specific offset past the bootloader? I'm not sure what the best course of action is here. All I know is that I rendered my Pinebook Pro unbootable through a command with a relatively innocuous-sounding name. (Yes, I should have looked up what this did first…)

**Comment by samueldr** [comment]
Oooh, that can get annoying to rescue depending on the device. Though it might be a misconfiguration on our side here. After all I had to change some settings for SPI from the defaults.

I'm currently taking time to $work on Mobile NixOS things, but will be taking some time in a not too distant future to work on Tow-Boot stuff again.

**Comment by plabadens** [comment]
I have not tried any of this, so I can't vouch for these instructions, but in principle you can flash the SPI from another PC, hopefully by getting into maskrom mode using the recovery button on the mainboard. I've also heard you can force it to boot on the SD/eMMC by shorting some pins, and then erase/flash the SPI from there.

https://wiki.pine64.org/wiki/Pinebook_Pro_SPI

**Comment by samueldr** [comment]
I haven't actively tried the maskrom button method, but shorting the pins for the SPI Flash works just fine.

Though I had assumed here @b- didn't need any help recovering, as they didn't ask :).

**Comment by b-** [comment]
Indeed, I actually came across Tow-Boot because of a bad SPI flash anyway. Thanks for the help, though!

Edit: also my PBP has a 0% rate of booting to maskrom via the recovery button, which seems to do a lot of nothing. However, what _does_ work rather reliably is simply putting a bootable SD in, turning off the eMMC switch, and shorting the SPI flash while pressing the reset button. No need to deal with rkdeveloptool or maskrom mode.

**Comment by samueldr** [comment]
It was stated as being equivalent to shorting the SPI pins in some documentations. But it does not work to skip SPI boot. My assumption is that there is a hardware bug that makes it not work as expected.

I can boot to maskrom mode successfully by having no valid *initial boot firmware* to boot though. So none in SPI, none in eMMC, and none in SD. I actually have to look into building Tow-Boot so that it is bootable through "maskrom" as it would facilitate development some more :).

**Comment by samueldr** [comment]
If you build from #34, `saveenv` and `env save` work as expected on the boards I have tested

 - Pine A64-LTS (a64)
 - AML-S805X-AC (S805X)
 - ROC-RK3399-PC (rk3399)

Given that I never have seen a difference so fundamental between any rk3399 boards, I assume it's fixed for the Pinebook Pro. I'm unable to test just at the moment.

My testing included using `saveenv` on all those three boards. And verifying it loads the new environment.

(Side-note: By design, any non-SPI installs don't support reading/saving environment anymore.)
